### ISSUE TITLE
Running download script on a shared server results in an error.

### ISSUE THREAD

**Issue by koenkarsten** [v12mike/fetch-external-images#2]
I've had success in using this script on various VPS's with phpBB installed, but sadly I can't get it to work on a virtual shared server. When running the download script on a shared server it produces the following output (limited to 1 `MAXIMUM_FILES_TO_FETCH`):
```
[phpBB Debug] PHP Warning: in file [ROOT]/scripts/download_external_images.php on line 107: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set
status 0 FAIL : http://i60.photobucket.com/<rest_of_url>.jpg
```
I believe it's common practice to set an open_basedir on shared servers, so this probably affects more servers then just the one I'm trying to fix now. Removing line 107 or setting it to 0 instead of 1 doesn't work either, since the script then can't fetch the image from the 3rd party hosting site.

**Comment by koenkarsten** [comment]
I'm currently looking into replacing curl with another PHP HTTP lib, but would like to hear any thoughts on how to best tackle this issue.

**Comment by v12mike** [comment]
I am on holiday now, so don't have access to a system for testing.  I would 
suggest that you clone the phpbb database to a real machine or VPS, run the 
scripts, then copy the image files back to the original system.

**Comment by deejayses** [comment]
Hi, I've tried this script, but it does not work correctly.
The modified database is correct, since I can see the links, but they are not downloaded in the folder.
My version of php is 5.6.40 and phphbb 3.2.4
I am testing on localhost using a sysnology server.

the result of the php is :
status 0 FAIL: https://www.topandroid.com/Imagenes/emulador-de-juego-nds4droid.jpg status 0 FAIL: https://www.topandroide.com/Imagenes/app-mupen64-plus-ae-para -jugar-n64.jpg status 0 FAIL: https://www.topandroide.com/Imagenes/app-emulador-de-juego-supergnes-para-android.jpg status 0 FAIL: https://www.topandroide.com /Imagenes/my-boy-un-emulador-de-juego-para-android.jpg status 0 FAIL: http://i32.photobucket.com/albums/d24/hamiltw/1908packwood.jpg All Done !!

But do not create any image files and I have modified the permissions in the folder.
Any suggestions?
a greeting

Working in [foro mas que consolas](http://masqueconsolas.net/)

**Comment by v12mike** [comment]
I think that most of those links are actually broken for one reason or another (try them in your browser)
I think that someone else did report an issue with the script running on php v5.6 (I run v7.1), but I can't locate the details at present.
